README.md

Added the following services to this list:
ProtonVPN
IVPN
TAILS OS
Qubes OS
Whonix
CalyxOS
kycnot.me
trocador.app
SISMO
I considered adding a lot of open-source hardware wallets under #Wallets but saw that most of the options are software wallets. Did not add these here.
I would propose to remove the list the following @Msiusko: Concordium  - not private, it's a closed blockchain for something they call RegDeFi MobileCoin  - not private
GRIN  - not private
BAT token - not private

Added services to this list

---

README.md

Adds tools for Ethereum nodes and private social networks

Add some stuff

---

README.md

Improved explanation about my project Plebble

Update README.md - Plebble

---

README.md

Thanks for this comprehensive list highlighting web3 privacy systems!
There are quite a few projects that I'm going to check out now because of the list :) 
Added RAILGUN to the DeFi section, near Aztec and Panther which are the closest equivalents.
railgun.org / docs.railgun.org
Contact me @therealjmj on Telegram with any questions, cheers!

JMJ - Add Railgun to DeFi section

---

README.md

Added BOB Protocol to Currency section just after another stable coin.
BOB token on CoinGecko: https://www.coingecko.com/en/coins/bob
Documentation: https://docs.zkbob.com/
GitHub: https://github.com/zkBob
BOB token on
- Polygon: https://polygonscan.com/token/0xB0B195aEFA3650A6908f15CdaC7D92F8a5791B0B
- Ethereum Mainnet: https://etherscan.io/token/0xB0B195aEFA3650A6908f15CdaC7D92F8a5791B0B
- Optimism: https://optimistic.etherscan.io/token/0xB0B195aEFA3650A6908f15CdaC7D92F8a5791B0B
- BNB Smart Chain: https://bscscan.com/token/0xB0B195aEFA3650A6908f15CdaC7D92F8a5791B0B

add: BOB Protocol

---

README.md

0xTIP - Private bridge from Ethereum to BNB chain, tip bot, and mixer mixer built by 0xMonero.

Add Bridge 0xTIP (0xMonero)

---

ZKprivacylandscape/Readme.md

Added Hush, DragonX, and alphabetized some things.

Updating ZK

---

README.md
ZKprivacylandscape/Readme.md

add Firn Protocol to the main README, as well as to the ZK Privacy Landscape section.

add firn protocol

---

README.md

Add vault1317 as a protocol and lurch1317 as one of implementation of vault1317

Add Vault1317 & lurch1317

---

README.md

Removed some duplicates, added some url links
Removed some coingecko html code present at the end of some descriptions that showed the Ethereum logo on these entries.
Tabulated (markdown editing) the content of sections that were missing. Did not tabulate 'Other' as these will probably be added to other sections in future. 
Took the opportunity to move the entire list that is the 'Other' section at the end, which ends before the 'Events' section.  Seemed the most logical arrangement for the content

Tabluated entries & removed some content

---

README.md

Update network status and other information

Update Session Information

---

README.md

Formatted the table for the 'Other' section of the README.md
Added link to CakePay (missing url)
Added link to nostr procotol github (missing url)
Added following items to Podcasts & Blogs
https://freedom.tech/
https://surveillancereport.tech/
Added KYCP (under KYC) and Gitcoin Passport (under DID)

Formatted table + added entries

---

Web3privacynowplatform/scoringmodel/DeFi category prototype.md

Deleted 'Ecosystem' as a table column and all entries in the respective entries since this value is not necessary for scoring the platforms

Update DeFi category prototype.md

---

README.md

As mentioned I have added the latest information about Brave to the Database.

docs: add up-to-date information of Brave browser to Database

---

README.md

L2: Laser Beam
DID: BANS
DAO: BeamX DAO
Bridge: Beam Eth Bridge
Messaging: BAM

Beamprivacy

---

.vscode/settings.json
README.md

Adds:
- [Rarimo Protocol](https://rarimo.com/) to the "DID" section
- [Freedom Tool](https://freedomtool.org/#/) to the "Other" section

Added Rarimo and Freedom Tool entries

---

Web3privacynowplatform/Briefs/Tangle.md

Reference Issue https://github.com/webb-tools/tangle/issues/519

Update Tangle brief

---

README.md

Also add the protocols from https://github.com/web3privacy/web3privacy/pull/65 to main readme

Add 5 zk protocols to main readme

---

Market overview/Ethereum Ecosystem/Hackathon projects.md

adding the rest of ethglobal hackathons from 2021-2024 that contain (what i can surmise are) privacy hackathon projects

add ethglobal 2021-2024 hackathons

---

README.md

Adds the [Ambire wallet](https://www.ambire.com/) to the Wallet category.

Add Ambire wallet

---

Web3privacynowplatform/Readme.md

This pull request contains changes to improve clarity, correctness and structure.
Description correction:
Corrected `reserach` to `research`
Corrected `feddback` to `feedback`
Corrected `aplicability` to `applicability`
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

Market overview/Ethereum Ecosystem/Readme.md
README.md
Web3privacynowplatform/Briefs/Threshold.md

updated two readme's for Threshold Network
added Brief for Threshold Network

Threshold Network update readme + Brief

---

Market overview/Ethereum Ecosystem/Ethereum privacy funding.md

I have added new data from the Giveth regarding the privacy focused projects and funding recieved by them via Giveth.

Update Ethereum privacy funding.md

---

Web3privacynowplatform/Briefs/Waku.md
Web3privacynowplatform/scoringmodel/Data brief & scoring model comparison.md
Web3privacynowplatform/scoringmodel/DeFi category prototype.md

This pull request introduces the following changes:
- Added "Sign-in requirements" section to the scoring model for both general and MVP-specific evaluations.
- Updated the privacy policy, collected data, and data sharing sections to reflect the latest scoring criteria.
- Enhanced clarity on identity integrations within the scoring model.
These changes aim to improve the comprehensiveness of the scoring model and ensure that all relevant aspects are considered in the evaluation process.

Add Sign-in Requirements and Update Scoring Model

---

Market overview/Ethereum Ecosystem/Hackathon projects.md
Market overview/Ethereum Ecosystem/R&D.md
Market overview/Ethereum Ecosystem/Readme.md
Web3privacynowplatform/Briefs/Brief 2.0.md
Web3privacynowplatform/Briefs/Brume.md

applicatiSmart - application. A smart
2020-09-044 - 2020-09-04
EVM-comatible  - EVM-compatible
Complience - Compliance
Complience - Compliance

fix spelling issues

---

Market overview/Ethereum Ecosystem/Hackathon projects.md
Market overview/ZK privacy landscape/Readme.md
Web3privacynowplatform/Briefs/Brief 2.0.md
Web3privacynowplatform/Briefs/Fileverse.md
Web3privacynowplatform/Briefs/Lit.md
Web3privacynowplatform/Briefs/Railgun.md

Market overview/Ethereum Ecosystem/Hackathon projects.md
legal feen - legal fees  --`fix typo and deleted missing space`
Market overview/ZK privacy landscape/Readme.md
unparalelled - unparalleled --` fix typo`
Web3privacynowplatform/Briefs/Brief 2.0.md
aplicable - applicable -- `fix typo x3`
Web3privacynowplatform/Briefs/Fileverse.md
aplicable - applicable -- `fix typo x3`
Web3privacynowplatform/Briefs/Lit.md
Complience - Compliance -- `fix typo`
Web3privacynowplatform/Briefs/Railgun.md
Complience - Compliance -- `fix typo`

chore: fix typos

---

README.md

link-Update README.md

---

Web3privacynowplatform/Readme.md

replace dead reference 

---

Market overview/Ethereum Ecosystem/Hackathon projects.md

Hello Team, I fixed some typos in Hackathon projects.md.

Fix Typos in Hackathon projects.md

---

README.md

Qash is an end-to-end private global payroll solution.

docs: Add Qash (Private Payroll)
